spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jisik_sponsor_spring?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: fhrzl1414!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6